"""nomos

Revision ID: 1ece149bf163
Revises: 
Create Date: 2026-06-21 06:41:46.907185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ece149bf163'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('facts', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('decision_gaps', sa.Text(), nullable=True),
    sa.Column('final_judgment', sa.Text(), nullable=True),
    sa.Column('logical_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_case_id'), 'court_case', ['id'], unique=False)
    op.create_table('kb_clause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cl_ident', sa.String(length=100), nullable=True),
    sa.Column('cl_description', sa.Text(), nullable=True),
    sa.Column('cl_category', sa.Enum('definicja', 'baza', name='clcategory'), nullable=True),
    sa.Column('cl_view_name', sa.String(length=100), nullable=True),
    sa.Column('cl_net', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_clause_cl_ident'), 'kb_clause', ['cl_ident'], unique=True)
    op.create_table('kb_external',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=100), nullable=True),
    sa.Column('api', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=45), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('url_def', sa.String(length=256), nullable=True),
    sa.Column('cron', sa.String(length=256), nullable=True),
    sa.Column('gus_par', sa.String(length=10), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_external_par',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('par_ident', sa.String(length=100), nullable=True),
    sa.Column('par_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('law_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('formal_proof', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_project_id'), 'law_project', ['id'], unique=False)
    op.create_table('predicate',
    sa.Column('predicate_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('logic_expression', sa.Text(), nullable=True),
    sa.Column('short_answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('predicate_id')
    )
    op.create_index(op.f('ix_predicate_predicate_id'), 'predicate', ['predicate_id'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    op.create_table('question_predicate_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('predicate_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_predicate_mapping_id'), 'question_predicate_mapping', ['id'], unique=False)
    op.create_table('referendum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('value_a', sa.String(length=100), nullable=False),
    sa.Column('value_b', sa.String(length=100), nullable=False),
    sa.Column('votes_a', sa.Integer(), nullable=True),
    sa.Column('votes_b', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referendum_id'), 'referendum', ['id'], unique=False)
    op.create_table('semantic_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_edge_id'), 'semantic_edge', ['id'], unique=False)
    op.create_table('semantic_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=True),
    sa.Column('fuzzy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_node_id'), 'semantic_node', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_node_name'), 'semantic_node', ['name'], unique=True)
    op.create_table('kb_clause_par',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=True),
    sa.Column('par_ident', sa.String(length=100), nullable=True),
    sa.Column('par_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['kb_clause.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_clause_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['kb_clause.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_project_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['law_project_id'], ['law_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_report_id'), 'verification_report', ['id'], unique=False)
    op.create_table('kb_clause_sub_par',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_sub_id', sa.Integer(), nullable=True),
    sa.Column('par_ident', sa.String(length=100), nullable=True),
    sa.Column('unify_cl', sa.String(length=100), nullable=True),
    sa.Column('unify_par', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('cut', sa.Boolean(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['clause_sub_id'], ['kb_clause_sub.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_clause_sub_par')
    op.drop_index(op.f('ix_verification_report_id'), table_name='verification_report')
    op.drop_table('verification_report')
    op.drop_table('kb_clause_sub')
    op.drop_table('kb_clause_par')
    op.drop_index(op.f('ix_semantic_node_name'), table_name='semantic_node')
    op.drop_index(op.f('ix_semantic_node_id'), table_name='semantic_node')
    op.drop_table('semantic_node')
    op.drop_index(op.f('ix_semantic_edge_id'), table_name='semantic_edge')
    op.drop_table('semantic_edge')
    op.drop_index(op.f('ix_referendum_id'), table_name='referendum')
    op.drop_table('referendum')
    op.drop_index(op.f('ix_question_predicate_mapping_id'), table_name='question_predicate_mapping')
    op.drop_table('question_predicate_mapping')
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_predicate_predicate_id'), table_name='predicate')
    op.drop_table('predicate')
    op.drop_index(op.f('ix_law_project_id'), table_name='law_project')
    op.drop_table('law_project')
    op.drop_table('kb_external_par')
    op.drop_table('kb_external')
    op.drop_index(op.f('ix_kb_clause_cl_ident'), table_name='kb_clause')
    op.drop_table('kb_clause')
    op.drop_index(op.f('ix_court_case_id'), table_name='court_case')
    op.drop_table('court_case')
    # ### end Alembic commands ###
